#!/bin/bash

TMP_DIR=/tmp/hps-ldap-confs
LDAP_PASSWORD=pnideldap_123456
#LDAP_IP=172.16.1.14
LDAP_IP=localhost

echo "[HUAYRA PNIDE SERVIDOR] - Configurando slapd"

echo "slapd slapd/domain string primariadigital.local" | debconf-set-selections
echo "slapd slapd/organization string primariadigital.local" | debconf-set-selections
echo "slapd slapd/password1 password $LDAP_PASSWORD" | debconf-set-selections
echo "slapd slapd/password2 password $LDAP_PASSWORD" | debconf-set-selections
echo "slapd slapd/internal/generated_adminpw password $LDAP_PASSWORD" | debconf-set-selections
echo "slapd slapd/internal/adminpw password $LDAP_PASSWORD" | debconf-set-selections
echo "slapd shared/organization	string primariadigital.local" | debconf-set-selections
echo "slapd slapd/move_old_database boolean true" | debconf-set-selections
echo "slapd slapd/dump_database_destdir string /var/backups/" | debconf-set-selections
echo "slapd slapd/allow_ldap_v2 boolean false" | debconf-set-selections
echo "slapd slapd/backend string HDB" | debconf-set-selections 
rm -rf /var/backups/*
dpkg-reconfigure -f noninteractive slapd


ldapadd -c -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/core.ldif
ldapadd -c -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/cosine.ldif
ldapadd -c -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/nis.ldif
ldapadd -c -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/inetorgperson.ldif

mkdir -p $TMP_DIR
rm -rf $TMP_DIR/*

echo "dn: cn=config
changetype: modify
replace: olcLogLevel
olcLogLevel: 256" > $TMP_DIR/loglevel.ldif

echo "dn: olcDatabase={1}hdb,cn=config
changetype: modify
add: olcDbIndex
olcDbIndex: uid eq" > $TMP_DIR/uid_eq.ldif

echo "dn: olcDatabase={0}config,cn=config
changetype: modify
add: olcAccess
olcAccess: to * by dn="cn=admin,dc=primariadigital,dc=local" write" > $TMP_DIR/access.ldif

ldapmodify -Y EXTERNAL -H ldapi:/// -f $TMP_DIR/loglevel.ldif 
ldapmodify -Y EXTERNAL -H ldapi:/// -f $TMP_DIR/uid_eq.ldif
ldapmodify -Y EXTERNAL -H ldapi:/// -f $TMP_DIR/access.ldif

echo "dn: ou=People,dc=primariadigital,dc=local
ou: People
objectClass: organizationalUnit

dn: ou=Group,dc=primariadigital,dc=local
ou: Group
objectClass: organizationalUnit" > $TMP_DIR/ou.ldif

echo "dn: cn=alumnos,ou=Group,dc=primariadigital,dc=local
cn: alumnos
gidNumber: 500
objectClass: posixGroup
objectClass: top" > $TMP_DIR/group_alumnos.ldif

echo "dn: uid=salvarez,ou=People,dc=primariadigital,dc=local
cn: Sebastian Alvarez
gidNumber: 500
givenName: Sebastian Alvarez
homeDirectory: /fs/salvarez
objectClass: inetOrgPerson
objectClass: extensibleObject
objectClass: posixAccount
objectClass: top
info: 1A
sn: Sebastian Alvarez
uid: salvarez
uidNumber: 1001
userpassword: {MD5}ICy5YqxZB1uWSwcVLSNLcA==" > $TMP_DIR/user_prueba.ldif

ldapadd -c -x -w $LDAP_PASSWORD -D cn=admin,dc=primariadigital,dc=local -f $TMP_DIR/ou.ldif
ldapadd -c -x -w $LDAP_PASSWORD -D cn=admin,dc=primariadigital,dc=local -f $TMP_DIR/group_alumnos.ldif
ldapadd -c -x -w $LDAP_PASSWORD -D cn=admin,dc=primariadigital,dc=local -f $TMP_DIR/user_prueba.ldif

echo "BASE  dc=primariadigital, dc=local" > /etc/ldap/ldap.conf
echo "URI ldap://$LDAP_IP/" >> /etc/ldap/ldap.conf
echo "TLS_CACERT	/etc/ssl/certs/ca-certificates.crt" >> /etc/ldap/ldap.conf

/etc/init.d/slapd restart
